### ISSUE TITLE
Suggestion to Add User Guide and Changelog

### ISSUE THREAD

**Issue by lylc0000** [mesteranas/AITranslater-nvda-add-on#2]
Hi, I recently discovered this plugin while browsing the NVDA Add-ons Store. Its ability to use AI models like GPT and Gemini for translation caught my attention. After downloading it, I noticed there was no Help menu available in the Add-ons Store under the plugin's Actions button.
I then visited this GitHub repository and read through the Readme, but I still couldn't figure out how to use it. It was only after checking the plugin's category in the NVDA Input Gestures menu that I finally understood how to operate it.
Today, I received a notification about an update from version 0.1 to 0.2. I was curious about what had changed, but unfortunately, there is still no Help menu in the NVDA Add-ons Store Actions button, and there is no changelog or upgrade notes available in the plugin's directory.
I hope you can consider adding a user guide and a changelog to improve the user experience.

**Comment by mesteranas** [comment]
thank you my friend i'll add the readme file in the next version 

this one will be next week

**Comment by lylc0000** [comment]
Thank you so much! I look forward to seeing this come to fruition soon and wish the project continued success and growth.
